import { BrowserModule } from '@angular/platform-browser';
import { NgModule,CUSTOM_ELEMENTS_SCHEMA  } from '@angular/core';
import { AppRoutingModule } from '@src/app/app-routing.module';
import { AppComponent } from '@src/app/app.component';
import { environment } from 'src/environments/environment';
import { RouterModule } from '@angular/router';
import { FormsModule} from '@angular/forms';
import { BsNavbarComponent } from '@src/app/bs-navbar/bs-navbar.component';
import { HomeComponent } from '@src/app/home/home.component';
import { ProductsComponent } from '@src/app/products/products.component';
import { StockComponent } from '@src/app/stock/stock.component';
import { CheckOutComponent } from '@src/app/check-out/check-out.component';
import { SuccessComponent } from '@src/app/success/success.component';
import { MyOrdersComponent } from '@src/app/my-orders/my-orders.component';
import { AdminProductsComponent } from '@src/app/admin/admin-products/admin-products.component';
import { AdminOrdersComponent } from '@src/app/admin/admin-orders/admin-orders.component';
import { LoginComponent } from '@src/app/login/login.component';
import {NgbModule} from '@ng-bootstrap/ng-bootstrap';
import { PartsService } from '@src/app/parts.service';
import { HttpModule, Http } from '@angular/http';
import { ChartsModule } from 'ng2-charts';

import { IonicModule } from '@ionic/angular';
import { CdkTableModule } from '@angular/cdk/table';
import { ExcessInventoryComponent } from '@src/app/excess-inventory/excess-inventory.component';
import { SkuPerformaceComponent } from '@src/app/sku-performace/sku-performace.component';
import { PerformanceValidComponent } from '@src/app/performance-valid/performance-valid.component';
import { ReactiveFormsModule } from '@angular/forms';
import { HttpClientModule } from '@angular/common/http';
import { AutoGeneratedComponent } from '@src/app/auto-generated/auto-generated.component';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { DataTableComponent } from './data-table/data-table.component';
import { FlexLayoutModule} from '@angular/flex-layout';
import { OverallComponent } from './overall/overall.component';
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome'
import {MatAutocompleteModule} from '@angular/material/autocomplete';
import {MatBadgeModule} from '@angular/material/badge';
import {MatBottomSheetModule} from '@angular/material/bottom-sheet';
import {MatButtonModule} from '@angular/material/button';
import {MatButtonToggleModule} from '@angular/material/button-toggle';
import {MatCardModule} from '@angular/material/card';
import {MatChipsModule} from '@angular/material/chips';
import {MatStepperModule} from '@angular/material/stepper';
import {MatDatepickerModule} from '@angular/material/datepicker';
import {MatDialogModule} from '@angular/material/dialog';
import {MatDividerModule} from '@angular/material/divider';
import {MatExpansionModule} from '@angular/material/expansion';
import {MatGridListModule} from '@angular/material/grid-list';
import {MatIconModule} from '@angular/material/icon';
import {MatFormFieldModule } from '@angular/material/form-field';
import {MatListModule} from '@angular/material/list';
import {MatMenuModule} from '@angular/material/menu';
import {MatNativeDateModule, MatRippleModule} from '@angular/material/core';
import {MatProgressBarModule} from '@angular/material/progress-bar';
import {MatProgressSpinnerModule} from '@angular/material/progress-spinner';
import {MatRadioModule} from '@angular/material/radio';
import {MatSelectModule} from '@angular/material/select';
import {MatSidenavModule} from '@angular/material/sidenav';
import {MatSliderModule} from '@angular/material/slider';
import {MatSlideToggleModule} from '@angular/material/slide-toggle';
import {MatSnackBarModule} from '@angular/material/snack-bar';
import {MatSortModule} from '@angular/material/sort';
import {MatTableModule,MatTableDataSource} from '@angular/material/table';
import {MatTabsModule} from '@angular/material/tabs';
import {MatToolbarModule} from '@angular/material/toolbar';
import {MatTooltipModule} from '@angular/material/tooltip';
import {MatTreeModule} from '@angular/material/tree';
import {MatCheckboxModule} from '@angular/material/checkbox';
import {MatInputModule} from '@angular/material/input';
import {MatPaginatorModule} from '@angular/material/paginator';
import { MainNavComponent } from './main-nav/main-nav.component';
import { LayoutModule } from '@angular/cdk/layout';
import { DashboardComponent } from './dashboard/dashboard.component';
import { PerformanceSummaryComponent } from './performance-summary/performance-summary.component';

@NgModule({
  declarations: [
    AppComponent,
    BsNavbarComponent,
    HomeComponent,
    CheckOutComponent,
    ExcessInventoryComponent,
    LoginComponent,
    MyOrdersComponent,
    AutoGeneratedComponent,
    DataTableComponent,
    MainNavComponent,
    ProductsComponent,
    DashboardComponent
    
  ],
  imports: [
    BrowserModule,
    IonicModule,
    FlexLayoutModule,
    FontAwesomeModule,
    BrowserAnimationsModule,
    CdkTableModule,
    ReactiveFormsModule,
    FormsModule,
    AppRoutingModule,
    NgbModule,
    HttpModule,
    HttpClientModule,
    ChartsModule,
    MatAutocompleteModule,
    MatBadgeModule,
    MatBottomSheetModule,
    MatButtonModule,
    MatButtonToggleModule,
    MatCardModule,
    MatCheckboxModule,
    MatChipsModule,
    MatFormFieldModule,
    MatStepperModule,
    MatDatepickerModule,
    MatDialogModule,
    MatDividerModule,
    MatExpansionModule,
    MatGridListModule,
    MatIconModule,
    MatInputModule,
    MatListModule,
    MatMenuModule,
    MatNativeDateModule,
    MatPaginatorModule,
    MatProgressBarModule,
    MatProgressSpinnerModule,
    MatRadioModule,
    MatRippleModule,
    MatSelectModule,
    MatSidenavModule,
    MatSliderModule,
    MatSlideToggleModule,
    MatSnackBarModule,
    MatSortModule,
    MatTableModule,
    MatTabsModule,
    MatToolbarModule,
    MatTooltipModule,
    MatTreeModule,
    RouterModule.forRoot([
      { path: '',component: ExcessInventoryComponent},
      { path: 'dashboard',component: DashboardComponent},
      { path: 'performance',component: PerformanceSummaryComponent},
      { path: 'products',component: ProductsComponent},
      { path: 'stock',component: StockComponent},
      { path: 'check-out',component: CheckOutComponent},
      { path: 'login', component: LoginComponent},
      { path: 'admin/products', component: AdminProductsComponent},
      { path: 'admin/orders', component: AdminOrdersComponent },
      { path: 'excess-inventory', component: HomeComponent },
      { path: 'sku-performace', component: SkuPerformaceComponent },
      { path: 'performance-validation', component: PerformanceValidComponent }, 
      { path: 'overall', component: OverallComponent }, 
      { path: 'data-table', component: DataTableComponent },
    ]),
    BrowserAnimationsModule,
    FontAwesomeModule,
    LayoutModule
  ],
  exports:[
    MatTableModule,  
    CdkTableModule,
    MatAutocompleteModule,
    MatBadgeModule,
    MatBottomSheetModule,
    MatButtonModule,
    MatButtonToggleModule,
    MatCardModule,
    MatCheckboxModule,
    MatChipsModule,
    MatStepperModule,
    MatDatepickerModule,
    MatDialogModule,
    MatDividerModule,
    MatExpansionModule,
    MatGridListModule,
    MatIconModule,
    MatInputModule,
    MatListModule,
    MatMenuModule,
    MatNativeDateModule,
    MatPaginatorModule,
    MatProgressBarModule,
    MatProgressSpinnerModule,
    MatRadioModule,
    MatRippleModule,
    MatSelectModule,
    MatSidenavModule,
    MatSliderModule,
    MatSlideToggleModule,
    MatSnackBarModule,
    MatSortModule,
    MatTableModule,
    MatTabsModule,
    MatToolbarModule,
    MatTooltipModule,
    MatTreeModule,],
  providers: [PartsService],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  bootstrap: [AppComponent]
})
export class AppModule { }
