import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { AppRoutingModule } from '@src/app/app-routing.module';
import { AppComponent } from '@src/app/app.component';
import { environment } from 'src/environments/environment';
import { RouterModule } from '@angular/router';
import { FormsModule} from '@angular/forms';


import { BsNavbarComponent } from '@src/app/bs-navbar/bs-navbar.component';
import { HomeComponent } from '@src/app/home/home.component';
import { ProductsComponent } from '@src/app/products/products.component';
import { StockComponent } from '@src/app/stock/stock.component';
import { CheckOutComponent } from '@src/app/check-out/check-out.component';
import { SuccessComponent } from '@src/app/success/success.component';
import { MyOrdersComponent } from '@src/app/my-orders/my-orders.component';
import { AdminProductsComponent } from '@src/app/admin/admin-products/admin-products.component';
import { AdminOrdersComponent } from '@src/app/admin/admin-orders/admin-orders.component';
import { LoginComponent } from '@src/app/login/login.component';
import {NgbModule} from '@ng-bootstrap/ng-bootstrap';
import { PartsService } from '@src/app/parts.service';
import { HttpModule, Http } from '@angular/http';
import { ChartsModule } from 'ng2-charts';


import { ExcessInventoryComponent } from '@src/app/excess-inventory/excess-inventory.component';
import { SkuPerformaceComponent } from '@src/app/sku-performace/sku-performace.component';
import { PerformanceValidComponent } from '@src/app/performance-valid/performance-valid.component';
import { ReactiveFormsModule } from '@angular/forms';
import { HttpClientModule } from '@angular/common/http';
import { AutoGeneratedComponent } from '@src/app/auto-generated/auto-generated.component';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';

@NgModule({
  declarations: [
    AppComponent,
    BsNavbarComponent,
    HomeComponent,
    CheckOutComponent,
    ExcessInventoryComponent,
    LoginComponent,
    MyOrdersComponent,
    AutoGeneratedComponent,
    
  ],
  imports: [
    BrowserModule,
    ReactiveFormsModule,
    FormsModule,
    AppRoutingModule,
    NgbModule,
    HttpModule,
    HttpClientModule,
    ChartsModule,
    RouterModule.forRoot([
      { path: '',component: HomeComponent},
      { path: 'products',component: ProductsComponent},
      { path: 'stock',component: StockComponent},
      { path: 'check-out',component: CheckOutComponent},
      { path: 'login', component: LoginComponent},
      { path: 'admin/products', component: AdminProductsComponent},
      { path: 'admin/orders', component: AdminOrdersComponent },
      { path: 'excess-inventory', component: ExcessInventoryComponent },
      { path: 'sku-performace', component: SkuPerformaceComponent },
      { path: 'performance-validation', component: PerformanceValidComponent }, ]),
    BrowserAnimationsModule
  ],
  providers: [PartsService],
  bootstrap: [AppComponent]
})
export class AppModule { }
